In [13]:
import os
os.environ["KERAS_BACKEND"] = "jax"
import keras

class SimpleDense(keras.Layer):

    def __init__(self, units, activation=None):
        super().__init__()
        self.units = units
        self.activation = activation

    def build(self, input_shape):
        batch_dim, input_dim = input_shape
        self.W = self.add_weight(shape=(input_dim, self.units),
                                 initializer="random_normal")
        self.b = self.add_weight(shape=(self.units,),
                                 initializer="zeros")

    def call(self, inputs):
        y = keras.ops.matmul(inputs, self.W) + self.b
        if self.activation is not None:
            y = self.activation(y)
        return y

In [14]:
my_dense = SimpleDense(units=32, activation=keras.ops.relu)
input_tensor = keras.ops.ones(shape=(2, 784))
output_tensor = my_dense(input_tensor)
print(output_tensor.shape)
print(input_tensor)
print(output_tensor)

(2, 32)
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[0.         1.4400818  0.6756638  1.027761   1.1506404  0.
  0.         0.         2.7057996  0.         0.         1.1651196
  0.27111605 2.3071568  0.         0.20306797 1.2871262  0.
  0.         0.33774704 0.         0.         0.         1.8749131
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         1.4400818  0.6756638  1.027761   1.1506404  0.
  0.         0.         2.7057996  0.         0.         1.1651196
  0.27111605 2.3071568  0.         0.20306797 1.2871262  0.
  0.         0.33774704 0.         0.         0.         1.8749131
  0.         0.         0.         0.         0.         0.
  0.         0.        ]]


In [15]:
from keras import layers
layer=layers.Dense(32,activation="relu")
input_tensor = keras.ops.ones(shape=(2, 784))
output_tensor = layer(input_tensor)
print(output_tensor.shape)
print(input_tensor)
print(output_tensor)

(2, 32)
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[1.3493452  0.9986507  0.266883   0.         1.6137692  0.
  2.1312828  0.         0.         1.2916023  0.         0.
  0.         0.         1.9310498  0.         2.033622   0.
  0.39315116 0.         0.         1.8734617  0.         0.
  0.90570796 1.0867581  0.9751371  1.286169   1.8214335  2.7293293
  0.6909151  0.        ]
 [1.3493452  0.9986507  0.266883   0.         1.6137692  0.
  2.1312828  0.         0.         1.2916023  0.         0.
  0.         0.         1.9310498  0.         2.033622   0.
  0.39315116 0.         0.         1.8734617  0.         0.
  0.90570796 1.0867581  0.9751371  1.286169   1.8214335  2.7293293
  0.6909151  0.        ]]
