In [6]:
# PyTorch (Meta)
# Constants

import torch

print(torch.ones(size=(2, 1)))
print(torch.zeros(size=(2, 1)))
print(torch.tensor([1, 2, 3]))


tensor([[1.],
        [1.]])
tensor([[0.],
        [0.]])
tensor([1, 2, 3])


In [8]:
# Random Tensors
print(torch.normal(
    mean=torch.zeros(size=(3, 1)),
    std=torch.ones(size=(3, 1))))

# Equivalent to tf.random.uniform(shape=(3, 1), minval=0., maxval=1.)
print(torch.rand(3, 1))

tensor([[ 0.4110],
        [-0.3834],
        [ 0.5178]])
tensor([[0.6688],
        [0.9894],
        [0.8931]])


In [10]:
# Like NumPy, PyTorch tensors are assignable
x = torch.zeros(size=(2, 1))
print(x)
x[0, 0] = 1
print(x)

tensor([[0.],
        [0.]])
tensor([[1.],
        [0.]])


In [ ]:
# Creating a PyTorch parameter (automatically tracked)
x = torch.zeros(size=(2, 1))
p = torch.nn.parameter.Parameter(data=x)

In [12]:
# Tensor operations 1/2

a = torch.ones((2, 2))
b = torch.square(a)
c = torch.sqrt(b)
d = b + c
e = torch.matmul(a, b)
f = torch.cat((a, b), axis=0)

print(b)
print(f)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [14]:
# Tensor operations 2/2

a = torch.ones((2, 2))
b = torch.ones((2, 2))
c = a + b
d = torch.square(c)
e = torch.sqrt(d)

print(c)
print(d)
print(e)

tensor([[2., 2.],
        [2., 2.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[2., 2.],
        [2., 2.]])


In [17]:
# Gradients

input_var = torch.tensor(3.0, requires_grad=True)  # required to compute gradients
result = torch.square(input_var)
result.backward()
gradient = input_var.grad
gradient


tensor(6.)

In [20]:
# Linear classifier

input_dim = 2
output_dim = 1

W = torch.rand(input_dim, output_dim, requires_grad=True)
b = torch.zeros(output_dim, requires_grad=True)


def model(inputs, W, b):
    return torch.matmul(inputs, W) + b


def mean_squared_error(targets, predictions):
    per_sample_losses = torch.square(targets - predictions)
    return torch.mean(per_sample_losses)


learning_rate = 0.1


def training_step(inputs, targets, W, b):
    predictions = model(inputs)  # Forward pass
    loss = mean_squared_error(targets, predictions)
    loss.backward()  # Compute gradients
    grad_loss_wrt_W, grad_loss_wrt_b = W.grad, b.grad  # Retrieve gradients
    with torch.no_grad(): # Updating model parameters
        W -= grad_loss_wrt_W * learning_rate
        b -= grad_loss_wrt_b * learning_rate
    W.grad = None # Reset parameter gradients
    b.grad = None # Reset parameter gradients
    return loss

In [19]:
class LinearModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.W = torch.nn.Parameter(torch.rand(input_dim, output_dim))
        self.b = torch.nn.Parameter(torch.zeros(output_dim))

def forward(self, inputs):
    return torch.matmul(inputs, self.W) + self.b

model = LinearModel()

torch_inputs = torch.tensor(inputs)
output = model(torch_inputs)

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

def training_step(inputs, targets):
    predictions = model(inputs)
    loss = mean_squared_error(targets, predictions)
    loss.backward()
    optimizer.step() # Simpler updating of model parameters
    model.zero_grad() # Simpler reset of parameter gradients (otherwise values will sum up)
    return loss

NameError: name 'inputs' is not defined